FROM ubuntu:18.04
LABEL maintainer="Ivan Andreev"

# Install dependencies (keep lists)
RUN set -eux \
    && apt-get update \
    && apt-get install -q -y --no-install-recommends \
        systemd dbus systemd-cron \
        software-properties-common \
        sudo iproute2 iputils-ping dnsutils \
        python python3 \
        locales apt-utils \
        rsyslog \
    && apt-get clean \
    && echo rm -rf /var/lib/apt/lists/* \
    && rm -rf /usr/share/doc /usr/share/man

# Adapt rsyslog for docker
RUN sed -i 's/^\($ModLoad imklog\)/#\1/' /etc/rsyslog.conf

# Fix potential UTF-8 errors with ansible-test.
RUN locale-gen en_US.UTF-8

# Create non-privileged user for Ansible
RUN set -eux \
    && groupadd -r ansible \
    && useradd -m -g ansible ansible \
    && usermod -aG sudo ansible \
    && sed -i "/^%sudo/s/ALL\$/NOPASSWD:ALL/g" /etc/sudoers

# Prevent high CPU zombie agetty with molecule
# https://github.com/geerlingguy/docker-ubuntu1804-ansible/issues/9
RUN rm -f /lib/systemd/system/systemd*udev* ; \
    rm -f /lib/systemd/system/getty.target

# Setup systemd
ENV container docker
COPY initctl_faker .
RUN chmod +x initctl_faker && rm -fr /sbin/initctl && ln -s /initctl_faker /sbin/initctl

VOLUME ["/sys/fs/cgroup", "/tmp", "/run"]
CMD ["/lib/systemd/systemd"]
