FROM ubuntu:16.04
LABEL maintainer="Ivan Andreev"

# Install dependencies
RUN set -eux \
    && apt-get update \
    && apt-get install -q -y --no-install-recommends \
        systemd dbus systemd-cron \
        software-properties-common \
        sudo iproute2 iputils-ping dnsutils \
        locales \
        rsyslog \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* \
    && rm -rf /usr/share/doc /usr/share/man

# Adapt rsyslog for docker
RUN sed -i 's/^\($ModLoad imklog\)/#\1/' /etc/rsyslog.conf

# Fix potential UTF-8 errors with ansible-test.
RUN locale-gen en_US.UTF-8

COPY initctl_faker .
RUN chmod +x initctl_faker && rm -fr /sbin/initctl && ln -s /initctl_faker /sbin/initctl

VOLUME ["/sys/fs/cgroup", "/tmp", "/run"]
CMD ["/lib/systemd/systemd"]
