FROM ubuntu:22.04
LABEL maintainer="Ivan Andreev"

# Install dependencies (keep lists)
RUN set -eux \
 && export DEBIAN_FRONTEND=noninteractive \
 && apt-get update \
 && apt-get install -qy --no-install-recommends \
     systemd dbus systemd-cron \
     software-properties-common \
     sudo iproute2 iputils-ping dnsutils \
     python3 \
     locales apt-utils \
     rsyslog \
 && apt-get clean \
 && echo rm -rf /var/lib/apt/lists/* \
 && rm -rf /usr/share/doc /usr/share/man

# Adapt rsyslog for docker
RUN sed -i.orig 's/^module.load="imklog"/#\0/' /etc/rsyslog.conf

# Fix potential UTF-8 errors with ansible-test.
# TODO Fix "character map file `UTF-8' not found"
RUN locale-gen en_US.UTF-8

# Create non-privileged user for Ansible
RUN set -eux \
    && groupadd -r ansible \
    && useradd -m -g ansible ansible \
    && usermod -aG sudo ansible \
    && sed -i "/^%sudo/s/ALL\$/NOPASSWD:ALL/g" /etc/sudoers

# Prevent high CPU zombie agetty with molecule
# https://github.com/geerlingguy/docker-ubuntu1804-ansible/issues/9
RUN rm -f /lib/systemd/system/systemd*udev* ; \
    rm -f /lib/systemd/system/getty.target

# Setup systemd
ENV container docker
COPY initctl_faker .
RUN chmod +x initctl_faker && rm -rf /sbin/initctl && ln -s /initctl_faker /sbin/initctl

VOLUME ["/sys/fs/cgroup", "/tmp", "/run"]
CMD ["/lib/systemd/systemd"]
