---
version: '3.9'
services:
  heimdall:
    image: linuxserver/heimdall:latest
    ports: [9999:80]
    volumes:
      - ${HOME}/var/heimdall:/config
      # mrcry:/config
    labels:
      com.centurylinklabs.watchtower.enable: 'true'
    healthcheck:
      test: ["CMD", "/bin/ls", "/config"]
      interval: 1m
      timeout: 10s
      retries: 3
    deploy:
      placement:
        constraints:
          - node.hostname == ampere
volumes:
  mrcry:
    driver: rclone
    driver_opts:
      remote: mrcry:heimdall
      allow_other: 'true'
      vfs_cache_mode: full
      vfs_write_back: 1s
      dir_cache_time: 10s
      poll_interval: 0
networks:
  default:
    name: backbone
    external: true
...
