---
version: '3'
services:
  portainer:
    image: portainer/portainer:1.24.0-alpine
    command: -H tcp://tasks.agent:9009 --tlsskipverify
    ports:
      - 5050:9000
    volumes:
      - ${HOME}/var/portainer/data:/data
      - ${HOME}/var/portainer/shared:/shared
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      placement:
        constraints:
          - node.role == manager
          - node.hostname == hardy
    networks:
      - admin-net
  agent:
    image: portainer/agent:1.0.0
    environment:
      AGENT_CLUSTER_ADDR: tasks.agent
      AGENT_PORT: 9009
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9009:9009
    networks:
      - admin-net
    deploy:
      mode: global
networks:
  admin-net:
    driver: overlay
volumes:
  portainer: {}
