---
version: '3.9'
services:
  siad:
    image: ghcr.io/siafoundation/siad:master
    environment:
      SIA_API_PASSWORD:
    command: -M gctwrfa
    ports:
      # port 9980 must be accessible on localhost but secured externally
      - 9980:9980
      # ports 9981-9984 must be open externally
      - 9981:9981
      - 9982:9982
      - 9983:9983
      - 9984:9984
    volumes:
      - ${HOME}/sia/siad:/sia-data
    deploy:
      placement:
        constraints: [node.hostname == ampere]
    labels:
      com.centurylinklabs.watchtower.enable: 'true'
networks:
  default:
    name: backbone
    external: true
...
