---
version: '3.2'
services:
  siad:
    image: ghcr.io/siafoundation/siad:master
    environment:
      SIA_API_PASSWORD:
    command: -M gctwrfa
    ports:
      # port 9980 must be accessible on localhost but secured externally
      - target: 9980
        published: 9980
        protocol: tcp
        mode: host
      # ports 9981-9984 must be open externally
      - 9981:9981
      - 9982:9982
      - 9983:9983
      - 9984:9984
    volumes:
      - keen:/sia-data
    deploy:
      placement:
        constraints: [node.hostname == hardy]
    labels:
      com.centurylinklabs.watchtower.enable: 'true'
volumes:
  keen:
    driver: vieux/sshfs
    driver_opts:
      sshcmd: root@10.33.3.11:/tmp/mnt/4g-all/sia/siad
      port: 32322
      identityFile: /root/.ssh/deex1.key
      cache: 'no'
...
