---
version: '3.9'
services:
  ssh:
    image: kroniak/ssh-client
    command: sh -c "cp -r /.ssh /root && exec ssh -L 0.0.0.0:9980:127.0.0.1:9980 -N ampere"
    ports:
      - target: 9980
        published: 9980
        protocol: tcp
        mode: host
    volumes:
      - ${HOME}/.ssh:/.ssh
    deploy:
      placement:
        constraints:
          - node.hostname == hardy
networks:
  default:
    name: backbone
    external: true
...
