---
version: '3'
services:
  trilium:
    image: zadam/trilium:latest
    ports: [8002:8080]
    volumes:
      - ${HOME}/var/trilium:/root/trilium-data
    deploy:
      placement:
        # live near our data files
        constraints: [node.hostname == hardy]
...
