---
version: '3.3'
services:
  visualizer:
    image: dockersamples/visualizer:latest
    volumes: [/var/run/docker.sock:/var/run/docker.sock]
    ports: [6060:8080]
    deploy:
      placement:
        constraints: [node.role==manager]
...
