---
name: create entware container
# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - master
    tags:
      - '*'
    paths:
      - 'entware/**'
  pull_request:

jobs:
  entware:
    name: build and push image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Build and Push
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login --username ivandeex --password-stdin
          repo=ivandeex/entware
          tm=`date +%y%m%d%H%M`
          docker build -t $repo:latest entware
          docker tag $repo:latest $repo:$tm
          for i in `seq 3`; do
            docker push $repo:$tm    || continue
            docker push $repo:latest || continue
            break
          done
          echo ok
...
