---
name: create entware container
# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - master
    tags:
      - '*'
    paths:
      - 'entware/**'
  pull_request:

jobs:
  entware:
    name: build and push image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Build and Push
        uses: docker/build-push-action@v1
        with:
          username: ivandeex
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ivandeex/entware
          path: entware
          tags: latest
          tag_with_ref: true
          tag_with_sha: true
...
